export const books = [
    {
      id: 1,
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      category: "Fiction",
      rating: 4.5,
      description: "A novel about the American dream and the roaring twenties.",
      pages: 180,
      publishedDate: "1925",
    },
    {
      id: 2,
      title: "1984",
      author: "George Orwell",
      category: "Sci-Fi",
      rating: 4.8,
      description: "A dystopian novel set in a totalitarian regime.",
      pages: 328,
      publishedDate: "1949",
    },
    {
      id: 3,
      title: "To Kill a Mockingbird",
      author: "Harper Lee",
      category: "Fiction",
      rating: 4.7,
      description: "A story of racial injustice in the Deep South.",
      pages: 281,
      publishedDate: "1960",
    },
    {
      id: 4,
      title: "A Brief History of Time",
      author: "Stephen Hawking",
      category: "Non-Fiction",
      rating: 4.6,
      description: "An overview of cosmology for the general public.",
      pages: 212,
      publishedDate: "1988",
    },
    {
      id: 5,
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      category: "Fantasy",
      rating: 4.9,
      description: "A fantasy adventure of Bilbo Baggins.",
      pages: 310,
      publishedDate: "1937",
    },
    {
      id: 6,
      title: "Sapiens",
      author: "Yuval Noah Harari",
      category: "Non-Fiction",
      rating: 4.7,
      description: "A history of humankind.",
      pages: 443,
      publishedDate: "2011",
    },
    {
      id: 7,
      title: "Brave New World",
      author: "Aldous Huxley",
      category: "Sci-Fi",
      rating: 4.2,
      description: "A futuristic society governed by technology and control.",
      pages: 268,
      publishedDate: "1932",
    },
    {
      id: 8,
      title: "The Alchemist",
      author: "Paulo Coelho",
      category: "Fiction",
      rating: 4.4,
      description: "A story of dreams, destiny, and self-discovery.",
      pages: 197,
      publishedDate: "1988",
    },
    {
      id: 9,
      title: "The Catcher in the Rye",
      author: "J.D. Salinger",
      category: "Fiction",
      rating: 4.0,
      description: "A tale of teenage rebellion and angst.",
      pages: 234,
      publishedDate: "1951",
    },
    {
      id: 10,
      title: "Steve Jobs",
      author: "Walter Isaacson",
      category: "Biography",
      rating: 4.6,
      description: "The life story of Apple's co-founder.",
      pages: 656,
      publishedDate: "2011",
    },
    {
      id: 11,
      title: "The Martian",
      author: "Andy Weir",
      category: "Sci-Fi",
      rating: 4.8,
      description: "An astronaut stranded on Mars.",
      pages: 369,
      publishedDate: "2011",
    },
    {
      id: 12,
      title: "Becoming",
      author: "Michelle Obama",
      category: "Biography",
      rating: 4.9,
      description: "Memoir of the former First Lady of the U.S.",
      pages: 448,
      publishedDate: "2018",
    },
    {
      id: 13,
      title: "Harry Potter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      category: "Fantasy",
      rating: 4.9,
      description: "The beginning of Harry Potter’s magical journey.",
      pages: 309,
      publishedDate: "1997",
    },
    {
      id: 14,
      title: "Educated",
      author: "Tara Westover",
      category: "Biography",
      rating: 4.7,
      description: "A memoir of breaking away from a survivalist family.",
      pages: 352,
      publishedDate: "2018",
    },
    {
      id: 15,
      title: "The Power of Habit",
      author: "Charles Duhigg",
      category: "Non-Fiction",
      rating: 4.5,
      description: "How habits work and how to change them.",
      pages: 371,
      publishedDate: "2012",
    },
    {
      id: 16,
      title: "Frankenstein",
      author: "Mary Shelley",
      category: "Fiction",
      rating: 4.1,
      description: "The story of Victor Frankenstein and his monstrous creation.",
      pages: 280,
      publishedDate: "1818",
    },
    {
      id: 17,
      title: "The Shining",
      author: "Stephen King",
      category: "Fiction",
      rating: 4.3,
      description: "A psychological horror novel set in a haunted hotel.",
      pages: 447,
      publishedDate: "1977",
    },
    {
      id: 18,
      title: "Dune",
      author: "Frank Herbert",
      category: "Sci-Fi",
      rating: 4.6,
      description: "An epic space opera about politics, religion, and power.",
      pages: 412,
      publishedDate: "1965",
    },
    {
      id: 19,
      title: "The Road",
      author: "Cormac McCarthy",
      category: "Fiction",
      rating: 4.1,
      description: "A bleak but touching tale of father and son.",
      pages: 287,
      publishedDate: "2006",
    },
    {
      id: 20,
      title: "Atomic Habits",
      author: "James Clear",
      category: "Non-Fiction",
      rating: 4.8,
      description: "Practical strategies to build good habits and break bad ones.",
      pages: 320,
      publishedDate: "2018",
    },
  ];